### ISSUE TITLE
ggmlv

### ISSUE THREAD

**Issue by 13331112522** [LinkSoul-AI/Chinese-Llama-2-7b#7]
能提供ggmlv3.0_q4_0版本吗

**Comment by znsoftm** [comment]
如果有llama2的ggml推理代码，就可以用它转换模型

**Comment by znsoftm** [comment]
ggml中需要手工搭建推理计算图，手工处理转换。这个估计有人正在或已经完成处理。

**Comment by shiyemin** [comment]
我们有人在处理了，不过因为是大家业余时间在弄，时间暂时不是特别可控。如果有已经完成的方案，欢迎随时提PR。另外，考虑到本repo的方案完全兼容官方的格式，所以应该可以复用其他team做的ggml方案。

**Comment by soulteary** [comment]
@s1w3 提交了 ggml 方案 https://github.com/LinkSoul-AI/Chinese-Llama-2-7b/commit/c2c1ce89a1ceccf4dc2ed2c3e2f3d6c9c1d0c77b 

如果你习惯用 docker 玩，也可以参考 https://zhuanlan.zhihu.com/p/645426799 来做你自己的镜像 @13331112522
