### ISSUE TITLE
能否做个API接口程序呢？非常感谢！

### ISSUE THREAD

**Issue by stuarthe** [LinkSoul-AI/Chinese-Llama-2-7b#8]
我试着套用ChatGLM2-6B的 api.py 
报错：AttributeError: 'LlamaModel' object has no attribute 'chat'

谢谢！

**Comment by shiyemin** [comment]
可以参考infer.py的格式修改api.py，我们也会尽快提供。

**Comment by shiyemin** [comment]
api.py已提供：https://github.com/LinkSoul-AI/Chinese-Llama-2-7b/blob/main/api.py

**Comment by stuarthe** [comment]
非常感谢！

**Comment by stuarthe** [comment]
实在是不好意思。现在很多应用都默认openai的API，像ChatGLM2-6B 也做了1个访openai_api.py , 我尝试修改应用到 Llma2-7B上，一直不成功。提示：AttributeError: 'LlamaModel' object has no attribute 'stream_chat' 
不知大佬能否修改一个openai格式的api, 以方便通用调用呢。鄙人也尽力了，因才疏学浅，不得不求大佬帮助，感谢之至！

**Comment by stuarthe** [comment]
> api.py已提供：https://github.com/LinkSoul-AI/Chinese-Llama-2-7b/blob/main/api.py

已验证，可以正常调用。
